### PR TITLE
git 2.9+ needs --allow-unrelated-histories flag

### PR DESCRIPTION
**Pull request by AlJohri**
http://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories/37938036#37938036

### CODE REVIEW

**Comment by jasonbartz** [comment]
@AlJohri did you test this with an older version of git?  Does the command succeed there?

**Comment by AlJohri** [comment]
@jasonbartz no, sorry I haven't.

here is my git version:

```
/usr/bin/git --version
git version 2.11.0 (Apple Git-81)
```

if this is necessary, I can give it a shot later. here's a link to the last version below 2.9 for future me to try: https://sourceforge.net/projects/git-osx-installer/files/git-2.8.1-intel-universal-mavericks.dmg/download

**Comment by jasonbartz** [comment]
@AlJohri Since it's just a doc, can you add a note in the comment above that it's 2.9 +?

**Comment by AlJohri** [comment]
@jasonbartz done

**Pull request merged**
